[package]
name = "bs58-codec"
version = "0.1.0"
authors = ["Kaichao <kaichaosuna@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
bs58 = "0.3.1"